### ISSUE TITLE
taro 开发的时候不能边改边开发工具实时刷新

### ISSUE THREAD

**Issue by xinjie16** [dcasia/mini-program-tailwind#29]
如题，tailwind 的一个乐趣之一就是边改边看，边看边改。但是不知道哪儿设置不对。sample里的例子也是如此，是需要加特殊指令吗？

**Comment by ItsRyanWu** [comment]
文档里有提到，热重载失效是微信开发者工具的 bug，该 bug 已在开发者工具预览版里被修复，至于有没有发布到正式版或者何时发布我暂时还没追踪相关的信息。详情请见：#3

**Comment by xinjie16** [comment]
谢谢！
