### ISSUE TITLE
taro 下的vue3 项目 view 控件 click事件不响应

### ISSUE THREAD

**Issue by xinjie16** [dcasia/mini-program-tailwind#30]
我把以前的taro项目改用mini-program-tailwind，发现界面组件不再响应@click事件。简单试了一下sample的代码，也是如此。不知道是不是有别的设置。

**Comment by ItsRyanWu** [comment]
你是不是记错了？Taro Vue 小程序中 click 事件对应的指令为 `@tap` 而不是 `@click`，参考：[Taro 规范](https://taro-docs.jd.com/taro/docs/vue-overall#taro-%E8%A7%84%E8%8C%83-1)
由于这个问题和插件没有关系，所以先关闭这条问题了。

**Comment by xinjie16** [comment]
建议您不加mini-program-tailwind插件的时候试试@click事件，新建一个全新的taro vue项目简单新增个@click事件就复现问题了。我之前用的taro社区里另外一款tailwind插件，他们没有解决w-1/2这样的问题，您这款解决了这些。
